site_name: "ContainerSSH: An SSH Server That Launches Containers"
site_url: "https://projects.pasztor.at/containerssh/"
repo_url: "https://github.com/janoszen/containerssh/"
edit_uri: "edit/stable/docs/"
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: True
      separator: "-"
theme:
  name: material
  custom_dir: .docs-theme
  font: false
  features:
    - navigation.tabs
    - navigation.instant
    - toc.autohide
    - search.suggest
    - search.highlight
  logo: images/logo.svg
  favicon: images/logo.svg
  include_search_page: true
  search_index_only: false

  highlightjs: true
  hljs_languages: []

  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
plugins:
  - search
  - macros
nav:
  - 'Home': 'index.md'
  - 'Use cases':
      - Web hosting: 'usecases/webhosting.md'
      - Learning environments: 'usecases/learning.md'
      - Honeypots: 'usecases/honeypots.md'
      - Security: 'usecases/security.md'
  - 'Getting started':
    - 'Quick Start': 'quickstart.md'
    - 'Installation': 'installation.md'
    - 'Configuration': 'configuration.md'
    - 'Authentication Server': 'authserver.md'
    - 'Configuration Server': 'configserver.md'
    - 'Selecting a Backend': 'backends.md'
    - 'The dockerrun Backend': 'dockerrun.md'
    - 'The kuberun Backend': 'kuberun.md'
    - FAQ: 'faq.md'
  - 'Advanced usage':
    - 'Creating an Image': 'image.md'
    - 'Logging': 'logging.md'
    - 'Metrics': 'metrics.md'
    - 'Hardening': 'hardening.md'
  - API's:
      - 'About the API': 'api/index.md'
      - 'The AuthConfig Server â­§': './api/authconfig/'
site_favicon: img/favicon.png
extra_css:
  - css/custom.css
copyright: >
  Copyright &copy; Janos Pasztor and Contributors
  | <a href="https://projects.pasztor.at/containerssh/privacy/">Privacy Policy</a>