dockerrun:
  host: unix:///var/run/docker.sock
  cacert: ""
  cert: ""
  key: ""
  config:
    container:
      hostname: ""
      domainname: ""
      user: ""
      attachstdin: false
      attachstdout: false
      attachstderr: false
      exposedports: {}
      tty: false
      openstdin: false
      stdinonce: false
      env: []
      cmd: []
      healthcheck: null
      argsescaped: false
      image: containerssh/containerssh-guest-image
      volumes: {}
      workingdir: ""
      entrypoint: []
      networkdisabled: false
      macaddress: ""
      onbuild: []
      labels: {}
      stopsignal: ""
      stoptimeout: null
      shell: []
    host: null
    network: null
    platform: null
    containername: ""
    subsystems:
      sftp: /usr/lib/openssh/sftp-server
    timeout: 1m0s
