kuberun:
  connection:
    host: kubernetes.default.svc
    path: /api
    username: ""
    password: ""
    serverName: ""
    certFile: ""
    keyFile: ""
    cacertFile: ""
    cert: ""
    key: ""
    cacert: ""
    bearerToken: ""
    bearerTokenFile: ""
    qps: 5
    burst: 10
    insecure: false
    timeout: 0s
  pod:
    namespace: default
    consoleContainerNumber: 0
    podSpec:
      volumes: []
      initcontainers: []
      containers:
        - name: shell
          image: containerssh/containerssh-guest-image
          command: []
          args: []
          workingdir: ""
          ports: []
          envfrom: []
          env: []
          resources:
            limits: {}
            requests: {}
          volumemounts: []
          volumedevices: []
          livenessprobe: null
          readinessprobe: null
          startupprobe: null
          lifecycle: null
          terminationmessagepath: ""
          terminationmessagepolicy: ""
          imagepullpolicy: ""
          securitycontext: null
          stdin: false
          stdinonce: false
          tty: false
      ephemeralcontainers: []
      restartpolicy: ""
      terminationgraceperiodseconds: null
      activedeadlineseconds: null
      dnspolicy: ""
      nodeselector: {}
      serviceaccountname: ""
      deprecatedserviceaccount: ""
      automountserviceaccounttoken: null
      nodename: ""
      hostnetwork: false
      hostpid: false
      hostipc: false
      shareprocessnamespace: null
      securitycontext: null
      imagepullsecrets: []
      hostname: ""
      subdomain: ""
      affinity: null
      schedulername: ""
      tolerations: []
      hostaliases: []
      priorityclassname: ""
      priority: null
      dnsconfig: null
      readinessgates: []
      runtimeclassname: null
      enableservicelinks: null
      preemptionpolicy: null
      overhead: {}
      topologyspreadconstraints: []
      sethostnameasfqdn: null
    subsystems:
      sftp: /usr/lib/openssh/sftp-server
    agentPath: /usr/bin/containerssh-agent
    disableAgent: false
    shellCommand: []
    disableCommand: false
  timeout: 1m0s
